<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Adminpage.aspx.cs" Inherits="Finalproject.Adminpage" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style>
        #admintable {
            border: solid;
            border-color: rosybrown;
            text-align: center;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:MultiView ID="MultiViewadmin" runat="server">
                <asp:View ID="View1" runat="server">
                    <table id="admintable">
                        <tr>
                            <td colspan="3"><b>Admin Login</b></td>
                        </tr>
                        <tr>
                            <td>UserName</td>
                            <td>
                                <asp:TextBox ID="txtadminname" runat="server"></asp:TextBox></td>
                            <td>
                                <asp:Label ID="lbladminname" runat="server" ForeColor="Red"></asp:Label>
                            </td>
                        </tr>
                        <tr>
                            <td>Password</td>
                            <td>
                                <asp:TextBox ID="txtadminpassword" runat="server" TextMode="Password"></asp:TextBox>
                            </td>
                            <td>
                                <asp:Label ID="lbladminpass" runat="server" ForeColor="Red"></asp:Label></td>

                        </tr>
                        <tr>
                            <td>
                                <asp:Button ID="adminloginbutton" runat="server" Text="Login" Width="61px" OnClick="adminloginbutton_Click" />

                            </td>
                            <td>
                                <asp:Button ID="adminlogoutbutton" runat="server" Text="Home" OnClick="adminlogoutbutton_Click" /></td>
                        </tr>
                        <tr>
                            <td colspan="3">
                                <asp:Label ID="lbladmin" runat="server"></asp:Label>
                            </td>
                        </tr>
                    </table>
                </asp:View>
                <asp:View ID="View2" runat="server">
                    Select catogory:<asp:DropDownList ID="ddladminsorting" runat="server" DataValueField="catogory_id" DataTextField="catogory_name" AutoPostBack="True">
                        <asp:ListItem Text="--Select--" Value="0"></asp:ListItem>
                        <asp:ListItem Text="Mobile" Value="1"></asp:ListItem>
                        <asp:ListItem Text="perfumes" Value="2"></asp:ListItem>
                        <asp:ListItem Text="Bags" Value="3"></asp:ListItem>
                    </asp:DropDownList>
                    <asp:GridView ID="gvadmin" runat="server" AutoGenerateColumns="true" DataKeyNames="product_id" AutoGenerateDeleteButton="True" OnRowDeleting="gvadmin_RowDeleting" OnRowDataBound="onrowdatabound" OnSelectedIndexChanged="gvadmin_SelectedIndexChanged">
                        <Columns>
                            <asp:TemplateField HeaderText="UpdateProducts">
                                <ItemTemplate>
                                    <asp:LinkButton Text="Edit" ID="lnkSelect" runat="server" CommandName="Select" />
                                </ItemTemplate>
                            </asp:TemplateField>
                        </Columns>
                    </asp:GridView>
                    <asp:TextBox ID="txtproductnameupdate" runat="server"></asp:TextBox>
                    <asp:TextBox ID="txtpriceupdate" runat="server" TextMode="Number"></asp:TextBox>
                    <%--<asp:RegularExpressionValidator ID="RegularExpressionValidatornumber" runat="server" ErrorMessage="Only Number allowed" ForeColor="Red" ControlToValidate="txtpriceupdate" Display="Dynamic"></asp:RegularExpressionValidator>--%>
                    <asp:Button ID="priceupdatebutton" runat="server" Text="Update" OnClick="priceupdatebutton_Click" />
                    <asp:TextBox ID="txtproductidinvisible" runat="server" ReadOnly="True" Visible="False"></asp:TextBox>
                    <br />
                    <asp:Button ID="logoutbutton" runat="server" Text="Logout" OnClick="logoutbutton_Click" />
                    <asp:Button ID="AddNewProductbutton" runat="server" Text="Add New Product" OnClick="AddNewProductbutton_Click" />
                    <asp:Label ID="lbladmindbstatus" runat="server"></asp:Label>
                </asp:View>
                <asp:View ID="View3" runat="server">
                    Product Catogory
                    <asp:DropDownList ID="ddladdproduct" runat="server"
                        DataValueField="catogory_id" DataTextField="catogory_name">

                        <asp:ListItem Text="Select" Value="0"></asp:ListItem>
                        <asp:ListItem Text="Mobile" Value="1"></asp:ListItem>
                        <asp:ListItem Text="perfumes" Value="2"></asp:ListItem>
                        <asp:ListItem Text="Bags" Value="3"></asp:ListItem>

                    </asp:DropDownList>
                    Product Name:<asp:TextBox ID="txtproductname" runat="server"></asp:TextBox>
                    Product Price:<asp:TextBox ID="txtproductprice" runat="server"></asp:TextBox>
                    <br />
                    <asp:Button ID="insertbutton" runat="server" Text="Add product" OnClick="insertbutton_Click" />
                    <asp:Button ID="Backbutton" runat="server" Text="Back" OnClick="Backbutton_Click" />
                    <br />
                    <asp:Label ID="lbladdproduct" runat="server"></asp:Label>
                </asp:View>

            </asp:MultiView>
        </div>

    </form>
</body>
</html>
